(() => {
 const form=document.querySelector('#reserveForm'); if(!form)return; const API=window.AFTR_API_URL||''; let blocks=[];
 const date=document.querySelector('#rDate'),start=document.querySelector('#rStart'),end=document.querySelector('#rEnd'),msg=document.querySelector('#reserveAvailabilityMessage');
 const pad=n=>String(n).padStart(2,'0'); const today=new Date(); date.min=`${today.getFullYear()}-${pad(today.getMonth()+1)}-${pad(today.getDate())}`;
 const mins=t=>{const [h,m]=String(t).split(':').map(Number);return h*60+m}; const overlap=(a,b,c,d)=>Math.max(mins(a),mins(c))<Math.min(mins(b),mins(d));
 async function load(){if(!API)return;try{const r=await fetch(API+'?action=availability',{cache:'no-store'});const d=await r.json();blocks=d.blocks||[];}catch{}}
 function check(){if(!date.value){msg.textContent='Choose a date and time to check availability.';return false;}if(start.value&&end.value&&mins(end.value)<=mins(start.value)){msg.textContent='End time must be after start time.';msg.classList.add('blocked');return false;}const hits=blocks.filter(x=>x.date===date.value&&x.status!=='cancelled'&&start.value&&end.value&&overlap(start.value,end.value,x.start||'00:00',x.end||'23:59'));if(hits.length){msg.innerHTML='<strong>Booked / unavailable</strong><br>'+hits.map(x=>`${x.start} — ${x.end} · ${x.note||'Cafe booking'}`).join('<br>');msg.classList.add('blocked');return false;}msg.textContent='Available to request — AFTR will confirm the table.';msg.classList.remove('blocked');return true;}
 [date,start,end].forEach(x=>x.addEventListener('change',check)); load().then(check);
 form.addEventListener('submit',async e=>{e.preventDefault();if(!check())return;const obj={action:'booking',type:'Table reservation',name:document.querySelector('#rName').value.trim(),phone:document.querySelector('#rPhone').value.trim(),email:document.querySelector('#rEmail').value.trim(),guests:document.querySelector('#rGuests').value.trim(),message:document.querySelector('#rMessage').value.trim(),slotLabel:`${date.value} · ${start.value} — ${end.value}`,date:date.value,start:start.value,end:end.value};const ok=document.querySelector('#reserveSuccess');if(!API){ok.textContent='AFTR backend is not connected.';ok.classList.add('show');return;}try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(obj)});const d=await r.json();if(!d.ok)throw new Error(d.error||'Submission failed');ok.textContent='Table request sent. AFTR will confirm your reservation with you.';ok.classList.add('show');form.reset();}catch(err){ok.textContent='Could not submit: '+err.message;ok.classList.add('show');}});
})();
